version: "3.9"
services:
    web:
        build: ./docker
        ports:
            - 8080:80
        volumes:
            - ./framework/www/html:/framework/www/html
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        privileged: true
        command: /sbin/init