version: "3.9"
services:
    web:
        build: ./nginx
        ports:
            - 8080:80
        volumes:
            - ./framework:/framework
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /framework
